//import pictures
import abhinavsri360 from "../../photos/abhinavsri360.jpg";
import AravindVNair99 from "../../photos/AravindVNair99.jpg";
import srilaasya from "../../photos/srilaasya.jpg";
import Aswin from "../../photos/Aswin.jpg";
import helios027 from "../../photos/helios027.jpg";
import shawavisek35 from "../../photos/shawavisek35.png";
import karthik from "../../photos/karthik.jpg";
import MuhammadHassanRazaa from "../../photos/MuhammadHassanRazaa.jpg";
import advaithunnikrishnan from "../../photos/advaithunnikrishnan.jpg";
import AsishRaju from "../../photos/AsishRaju.jpg";
import Aineshphanithi from "../../photos/Aineshphanithi.jpg";
import chrisft25 from "../../photos/chrisft25.jpg";
import subratkishoredutta from "../../photos/subratkishoredutta.jpg";
import Abhinavtb from "../../photos/Abhinavtb.jpeg";
import jemikp from "../../photos/jemikp.jpg";
import kartikbhushan from "../../photos/kartikbhushan.jpg";
import Aravindh020 from "../../photos/Aravindh020.jpeg";
import NaveenK from "../../photos/NaveenK.jpeg";
import KunalGehlot from "../../photos/kunalgehlot.jpg";
import adi10hero from "../../photos/adi10hero.jpg";
import ghpranav from "../../photos/ghpranav.jpg";
import dewanshrawat15 from "../../photos/dewanshrawat15.jpg";
import AdithyaAnilkumar from "../../photos/AdithyaAnilkumar.jpg";
import abhishek2x from "../../photos/abhishek2x.png";
import RyuuKenshi from "../../photos/RyuuKenshi.jpg";
import sunanda from "../../photos/sunanda.jpg";
import shreyasmalewar from "../../photos/shreyasmalewar.jpg";
import Jacob from "../../photos/Jacob.jpg";
import ashwinraj from "../../photos/ashwinraj.jpg";
import suyashsonawane from "../../photos/suyashsonawane.jpg";
import harshKumarKhatri from "../../photos/harshKumarKhatri.jpg";
import praddy2009 from "../../photos/praddy2009.jpg";
import AnmolKaur from "../../photos/AnmolKaur.png";
import venkyJayasurya from "../../photos/venkyjayasurya.jpg";
import pvsharshith from "../../photos/pvsharshith.jpg";
import akashshrivastava from "../../photos/akashshrivastava.jpg"
import sakshigrover from "../../photos/sakshigrover.jpeg"
import Vasundharashukla from "../../photos/Vasundharashukla.jpg";
import PragatiVerma from "../../photos/PragatiVerma.jpg";
import palak from "../../photos/pal-16.jpg";
import AkshaySharma008 from "../../photos/AkshaySharma008.jpg";
import AdityaBirangal from "../../photos/AdityaBirangal.jpg";
import ikoala21 from "../../photos/ikoala21.jpg";
import sangeetajha from "../../photos/SangeetaJha.jpg";
import akshita2k from "../../photos/akshita2k.jpg";
import taharh from "../../photos/taharh.jpg";
import AkashM from "../../photos/AkashM.jpg";

const data = [
  {
    longitude: 77.3653,
    latitude: 28.5192,
    batch: 2020,
    photo: abhinavsri360,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "UI/UX", "Cloud"],
    name: "Abhinav Srivastava",
    bio: "I write something colorful on something very dark.",
    url: "https://dsc.community.dev/jaypee-institute-of-information-technology-sec-128",
    chapterName: "Jaypee Institute of Information Technology, Sec - 128",
    github: "https://github.com/abhinavsri360",
    linkedin: "https://linkedin.com/in/abhinavsri360",
    twitter: "https://twitter.com/abhinavsri360",
    portfolio: "https://abhinavsri360.netlify.app",
  },

  {
    longitude: 73.856743,
    latitude: 18.520430,
    batch: 2020,
    photo: AdityaBirangal,
    region: "Asia",
    skills: ["App Dev", "UI/UX", "Cloud"],
    name: "Aditya Birangal",
    bio: "Lover of Technology!",
    url: "https://dsc.community.dev/mit-academy-of-engineering/",
    chapterName: "MIT Academy of Engineering, Pune",
    github: "https://github.com/AdityaBirangal",
    linkedin: "https://linkedin.com/in/AdityaBirangal",
    twitter: "https://twitter.com/AdityaBirangal",
    portfolio: "https://birangal.com",
  },

  {
    longitude: 77.391029,
    latitude: 28.535517,
    batch: 2020,
    photo: PragatiVerma,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "Cloud"],
    name: "Pragati Verma",
    bio: "May the code be with you!",
    url: "https://dsc.community.dev/jss-academy-of-technical-education-noida/",
    chapterName: "JSS Academy of Technical Education, Noida",
    github: "https://github.com/PragatiVerma18",
    linkedin: "https://www.linkedin.com/in/pragativerma18/",
    twitter: "https://twitter.com/pragati_verma18",
    portfolio: "http://pragativerma18.github.io/Resume",
  },
  {
    longitude: 83.2184815,
    latitude: 17.6868159,
    batch: 2020,
    photo: srilaasya,
    region: "Asia",
    skills: ["AI/ML", "Web Dev", "UI/UX"],
    name: "Sri Laasya Nutheti",
    bio: "Respect Existance or Expect Resistance",
    url: "https://dsc.community.dev/andhra-university-college-of-engineering",
    chapterName: "Andhra University College of Engineering",
    github: "https://github.com/srilaasya",
    linkedin: "https://linkedin.com/in/sri-laasya",
    twitter: "https://twitter.com/n_sri_laasya",
  },
  {
    "latitude": 26.293501,
    "longitude": 78.133331,
    "batch": 2020,
    "photo": AkshaySharma008,
    "region": "Asia",
    "skills": ["Web Dev", "Cloud"],
    "name": "Akshay Sharma",
    "bio": "I write code to build Useful stuff which helps people.",
    "url": "https://dsc.community.dev/army-institute-of-technology/",
    "chapterName": "Army Institute of Technology, Pune",
    "github": "https://github.com/AkshaySharma008",
    "linkedin": "https://linkedin.com/in/akshaysharma008",
    "twitter": "https://twitter.com/akshay8844",
    "portfolio": "https://akshaysharma.co.in"
  },
  {
    longitude: 77.6746238,
    latitude: 12.8950888,
    batch: 2020,
    photo: AravindVNair99,
    region: "Asia",
    skills: ["Web Dev", "Cloud"],
    name: "Aravind V. Nair",
    bio:
      "Full-stack Web Developer, Cloud Computing and Cybersecurity Enthusiast",
    url: "https://dsc.community.dev/amrita-school-of-engineering-bengaluru",
    chapterName: "Amrita School of Engineering, Bengaluru",
    github: "https://github.com/AravindVNair99",
    linkedin: "https://linkedin.com/in/AravindVNair99",
    twitter: "https://twitter.com/AravindVNair99",
  },
  {
    longitude: 74.9339,
    latitude: 13.183,
    batch: 2020,
    photo: RyuuKenshi,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "UI/UX"],
    name: "Arjun Sinha",
    bio: '"Shift" the "ctrl" to me and I will "alt" the world.',
    url: "https://dsc.community.dev/nmam-institute-of-technology/",
    chapterName: "NMAM Institute of Technology, Nitte",
    github: "https://github.com/ryuukenshi",
    linkedin: "https://linkedin.com/in/ryuukenshi",
    twitter: "https://twitter.com/ryuukenshi",
    portfolio: "http://ryuukenshi.github.io/",
  },
  {
    longitude: 77.03527,
    latitude: 28.60957,
    batch: 2020,
    photo: Aswin,
    region: "Asia",
    skills: ["Cloud"],
    name: "Aswin Kumar M",
    bio: "Never fear the Air.",
    url: "https://dsc.community.dev/bannari-amman-institute-of-technology/",
    chapterName: "Bannari Amman Institute of Technology, Sathyamangalam",
    github: "https://github.com/todcru",
    linkedin: "https://www.linkedin.com/in/aswin-kumar-m-83081b171/",
    twitter: "https://twitter.com/thisaswin",
  },
  {
    longitude: 86.9842256,
    latitude: 25.242453,
    batch: 2020,
    photo: helios027,
    region: "Asia",
    skills: ["Web Dev"],
    name: "Harsh Jain",
    bio: "Progate Community Intern",
    url: "https://dsc.community.dev/bhagalpur-college-of-engineering",
    chapterName: "Indian Institute of Information Technology, Bhagalpur",
    github: "https://github.com/helios027",
    linkedin: "https://linkedin.com/in/harshjain2710",
    twitter: "https://twitter.com/HarshJain027",
  },
  {
    longitude: 88.35736,
    latitude: 22.58969,
    batch: 2020,
    photo: shawavisek35,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "UI/UX", "Cloud", "AI/ML"],
    name: "Avisek Shaw",
    bio: "Commit the changes in your life otherwise you will loose them.",
    url:
      "https://dsc.community.dev/calcutta-institute-of-engineering-and-management",
    chapterName: "Calcutta Institute of Engineering and Management",
    github: "https://github.com/shawavisek35",
    linkedin: "https://linkedin.com/in/avisek-shaw-78136b196",
    twitter: "https://twitter.com/AvisekShaw6",
    portfolio: "https://avisekcode.netlify.app",
  },
  {
    longitude: 77.5945627,
    latitude: 12.9715987,
    batch: 2020,
    photo: karthik,
    region: "Asia",
    skills: ["Bleh"],
    name: "B K Karthik",
    bio: "ಠ益ಠ.",
    url: "https://dsc.community.dev/pes-university-ec-campus",
    chapterName: "PES University Electronic City Campus",
    github: "https://github.com/call-me-bk",
    linkedin: "https://linkedin.com/in/iamKarthikBK",
    twitter: "https://twitter.com/iamKarthikBK",
    portfolio: "https://www.nohello.com",
  },
  {
    longitude: 21.640339625980996,
    latitude: 47.54352832810872,
    batch: 2020,
    photo: MuhammadHassanRazaa,
    region: "Europe",
    skills: ["App Dev", "AI/ML"],
    name: "Muhammad Hassan Raza",
    bio:
      "A hardworking and resourceful individual seeking to work as a computer scientist with the ability to persuade and convince people about computer-related works.",
    url: "dsc.community.dev/university-of-debrecen-debreceni-egyetem-de/",
    chapterName: "University of Debrecen / Debreceni Egyetem DE",
    github: "https://github.com/MuhammadHassanRazaa",
    linkedin: "https://linkedin.com/in/sshthassanraza",
    twitter: "https://twitter.com/sshthassanraza",
  },
  {
    longitude: 76.990746,
    latitude: 8.549941,
    batch: 2020,
    photo: advaithunnikrishnan,
    region: "Asia",
    skills: ["Web Dev"],
    name: "Advaith U",
    bio: "Web Developer",
    url:
      "https://dsc.community.dev/mar-baselios-college-of-engineering-technology/",
    chapterName: "Mar Baselios College of Engineering and Technology",
    github: "https://github.com/advaith-unnikrishnan",
    linkedin: "https://linkedin.com/in/advaithu",
    twitter: "https://twitter.com/advaith_unni",
    portfolio: "https://advaithunnikrishnan.me",
  },
  {
    longitude: 83.376702,
    latitude: 17.781218,
    batch: 2020,
    photo: AsishRaju,
    region: "Asia",
    skills: ["Web Dev", "UI/UX"],
    name: "V Asish Raju",
    bio:
      "I would love to change the world, but they won’t give me the source code",
    url:
      "https://dsc.community.dev/gandhi-institute-of-technology-and-management-visakhapatnam-campus/",
    chapterName: "GITAM University, Vizag Campus",
    github: "https://github.com/AsishRaju",
    linkedin: "https://linkedin.com/in/asishraju",
    twitter: "https://twitter.com/asish_io",
  },
  {
    longitude: 78.337764,
    latitude: 17.465592,
    batch: 2020,
    photo: Aineshphanithi,
    region: "Asia",
    skills: ["Cloud", "UI/UX"],
    name: "Ainesh Phanithi",
    bio:
      "Engineering student and working towards software development. Can effortlessly articulate ideas, offer practical solutions and has a great sense of humour.",
    url: "https://dsc.community.dev/cvr-college-of-engineering",
    chapterName: "CVR College of Engineering",
    github: "https://github.com/Aineshphanithi",
    linkedin: "https://www.linkedin.com/in/ainesh-phanithi/",
    twitter: "https://twitter.com/",
  },
  {
    longitude: 72.877655,
    latitude: 19.075983,
    batch: 2020,
    photo: adi10hero,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "UI/UX", "Cloud", "AI/ML"],
    name: "Aditya Srivastava",
    bio: "Life Long Learner and a passionate programmer.",
    url:
      "https://dsc.community.dev/vivekanand-education-societys-institute-of-technology/",
    chapterName: "Vivekanand Education Society's Institute of Technology",
    github: "https://github.com/adi10hero",
    linkedin: "https://linkedin.com/in/adi10hero",
    twitter: "https://twitter.com/adi10hero",
    portfolio: "https://adi10hero.github.io/",
  },
  {
    longitude: 72.968139,
    latitude: 26.229923,
    batch: 2020,
    photo: KunalGehlot,
    region: "Asia",
    skills: ["AI/ML", "Web Dev", "IoT"],
    name: "Kunal Gehlot",
    bio:
      "B.Tech. 2021, Data Science enthusiast with extensive experience in building ML models using Python and JavaScript.",
    url: "https://dsc.community.dev/jiet-group-of-institutions/",
    chapterName: "JIET Group of Institutions",
    github: "https://github.com/KunalGehlot/",
    linkedin: "https://www.linkedin.com/in/gehlotk/",
    twitter: "https://twitter.com/zackcodesai",
  },
  {
    longitude: -88.177773,
    latitude: 13.48127,
    batch: 2020,
    photo: chrisft25,
    region: "South America",
    skills: ["Web Dev", "UI/UX"],
    name: "Christopher Fuentes",
    bio:
      "Backend Developer. Geek. Marketing enthusiast. Passionate about learning new stuff. ",
    url: "https://dsc.community.dev/universidad-gerardo-barrios",
    chapterName: "Universidad Gerardo Barrios",
    github: "https://github.com/chrisft25",
    linkedin: "https://linkedin.com/in/chrisft25",
    twitter: "https://twitter.com/chrisft25",
    portfolio: "https://chrisfuentes.me",
  },
  {
    longitude: 76.299881,
    latitude: 9.981636,
    batch: 2020,
    photo: Abhinavtb,
    region: "Asia",
    skills: ["Web Dev", "AI/ML"],
    name: "Abhinav T B",
    bio:
      "Tech explorer | passionate developer | loves to automate things | problem solving | CSE undergrad @CUSAT ",
    url:
      "https://dsc.community.dev/cochin-university-of-science-and-technology/",
    chapterName: "Cochin University of Science and Technology",
    github: "https://github.com/abhinav-TB",
    linkedin: "https://linkedin.com/in/abhinav-t-b-226172190/",
    twitter: "https://twitter.com/abhiGamez",
    portfolio: "https://portfolio.abhigamez.co/",
  },
  {
    longitude: 72.946,
    latitude: 20.5135,
    batch: 2020,
    photo: jemikp,
    region: "Asia",
    skills: ["App Dev"],
    name: "Jemik Patel",
    bio: "Constantly Learning!!",
    url: "https://dsc.community.dev/government-engineering-college-rajkot/",
    chapterName: "Government Engineering College, Rajkot",
    github: "https://github.com/jemikp",
    linkedin: "https://linkedin.com/in/jemikp",
    twitter: "https://twitter.com/jemik_patel",
    portfolio: "https://jemikpatel.me",
  },
  {
    longitude: 73.728036,
    latitude: 18.541527,
    batch: 2020,
    photo: kartikbhushan,
    region: "Asia",
    skills: ["Web Dev", "Cloud", "AI/ML"],
    name: "Kartik Bhushan",
    bio:
      "Computer Science student who loves to code and also hack. Want to do something illegal count me in . ",
    url: "https://dsc.community.dev/symbiosis-institute-of-technology/",
    chapterName: "Symbiosis Institute of Technology",
    github: "https://github.com/kartikbhushan",
    linkedin: "https://www.linkedin.com/in/kartik-bhushan-977a0716b/",
    twitter: "https://twitter.com/Kartik_Bush",
    portfolio: "https://kartikbhushan.github.io/Portfolio-Gatsby/",
  },
  {
    longitude: 80.178452,
    latitude: 13.04152,
    batch: 2020,
    photo: Aravindh020,
    region: "Asia",
    skills: ["Web Dev", "Cloud", "UI/UX"],
    name: "Aravind Balaji K K",
    bio: "Developer",
    url:
      "https://dsc.community.dev/srm-institute-of-science-and-technology-ramapuram/",
    chapterName: "SRM Institute of Science & Technology, Ramapuram Campus",
    github: "https://github.com/Aravindh020/",
    linkedin: "https://linkedin.com/in/Aravindh020/",
    twitter: "https://twitter.com/Aravindh020/",
    portfolio: "http://aravindh020.github.io/",
  },
  {
    longitude: 76.958896,
    latitude: 11.000897,
    batch: 2020,
    photo: NaveenK,
    region: "Asia",
    skills: ["UI/UX", "Front-End"],
    name: "Naveen K",
    bio: "UI Designer",
    url: "https://dsc.community.dev/sri-krishna-college-of-technology/",
    chapterName: "Sri Krishna College of Technology, Coimbatore",
    github: "https://github.com/NaveenKarunanidhi",
    linkedin: "https://www.linkedin.com/in/naveen-k-14b397170",
    twitter: "https://twitter.com/Naveenk4226",
  },
  {
    longitude: 76.6135129,
    latitude: 12.3165844,
    batch: 2020,
    photo: ghpranav,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "Cloud"],
    name: "Pranav Bedre G H",
    bio: "Computers, my sin of choice.",
    url: "https://dsc.community.dev/jss-science-technology-university-mysuru",
    chapterName: "JSS Science & Technology University, Mysuru",
    github: "https://github.com/ghpranav",
    linkedin: "https://linkedin.com/in/ghpranav",
    twitter: "https://twitter.com/bedre_pranav",
  },
  {
    longitude: 77.2070383,
    latitude: 28.6870221,
    batch: 2020,
    photo: dewanshrawat15,
    region: "Asia",
    skills: ["Web Dev", "App Dev", "UI/UX", "AI/ML", "Cloud"],
    name: "Dewansh Rawat",
    bio:
      "Full stack developer. Open source enthusiast. Love to build smart platforms for common day issues.",
    url:
      "https://dsc.community.dev/bharati-vidyapeeth-deemed-university-college-of-engineering-pune/",
    chapterName:
      "Bharati Vidyapeeth (Deemed University) College of Engineering, Pune",
    github: "https://github.com/dewanshrawat15",
    linkedin: "https://linkedin.com/in/dewanshrawat15",
    twitter: "https://twitter.com/dewanshrawat15",
    portfolio: "https://dewanshrawat.in",
  },
  {
    longitude: 76.32847,
    latitude: 10.028607,
    batch: 2020,
    photo: AdithyaAnilkumar,
    region: "Asia",
    skills: ["Web Dev", "App Dev", "UI/UX", "Cloud"],
    name: "Adithya Anilkumar",
    bio: "Loyalty.Trust.Respect",
    url:
      "https://dsc.community.dev/government-model-engineering-college-thrikkakara/",
    chapterName: "Government Model Engineering College, Thrikkakara",
    github: "https://github.com/adithyaanilkumar",
    linkedin: "https://linkedin.com/in/adithyaanilkumar",
    twitter: "https://twitter.com/adixthya",
    portfolio: "https://adithyaanilkumar.github.io",
  },
  {
    longitude: 81.012421,
    latitude: 26.851311,
    batch: 2020,
    photo: abhishek2x,
    region: "Asia",
    skills: ["Web Dev"],
    name: "Abhishek Srivastava",
    bio: "An Entrepreneur by nature and a developer by passion.",
    url: "https://dsc.community.dev/vellore-institute-of-technology-bhopal/",
    chapterName: "Vellore Institute of Technology Bhopal",
    github: "https://github.com/abhishek2x",
    linkedin: "https://www.linkedin.com/in/abhishek-srivastava-49482a190/",
    twitter: "https://twitter.com/Abhishe51428266",
    portfolio: "https://portfolio.abhisheksrivastava.me/",
  },
  {
    longitude: 73.874352,
    latitude: 18.5289,
    batch: 2020,
    photo: sunanda,
    region: "Asia",
    skills: ["AI/ML", "Web Dev"],
    name: "Sunanda Somwase",
    bio: "Always looking for opportunities!",
    url:
      "https://dsc.community.dev/pune-vidyarthi-grihas-college-of-engineering-and-technology-pune/",
    chapterName:
      "Pune Vidyarthi Griha's College of Engineering and Technology, Pune",
    github: "https://github.com/SunandaS76",
    linkedin: "https://www.linkedin.com/in/sunandasomwase/",
    twitter: "https://twitter.com/SSomwase",
  },
  {
    longitude: 76.902603,
    latitude: 8.5465,
    batch: 2020,
    photo: Jacob,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "AI/ML"],
    name: "Jacob Abraham",
    bio:
      "Enthusiastic and passionate about coding with a strong desire to the field of Data Science. Have had various experiences and knowledgable in Web development and App development. Skilled as a Competitive Coder and a Leader that takes charge.",
    url: "https://dsc.community.dev/college-of-engineering-trivandrum/",
    chapterName: "College of Engineering Trivandrum",
    github: "https://github.com/jacob13400",
    linkedin: "https://www.linkedin.com/in/jacob-abraham-3b4b05190/",
    twitter: "https://twitter.com/Jake_is_live",
    portfolio: "http://www.jacobabraham.me/",
  },
  {
    longitude: 79.00346884403419,
    latitude: 21.105388500457135,
    batch: 2020,
    photo: shreyasmalewar,
    region: "Asia",
    skills: ["AI/ML", "Web Dev"],
    name: "Shreyas Malewar",
    bio: "I like to Code and Connect. I'm an Artist, Author and an Engineer.",
    url: "https://dsc.community.dev/gh-raisoni-college-of-engineering/",
    chapterName: "G H Raisoni College of Engineering",
    github: "http://github.com/shreyasmalewar",
    linkedin: "https://www.linkedin.com/in/shreyasmalewar/",
    twitter: "https://twitter.com/ShreyasMalewar",
  },
  {
    longitude: 73.76168501642378,
    latitude: 18.651701772395466,
    batch: 2020,
    photo: suyashsonawane,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "Machine Learning"],
    name: "Suyash Sonawane",
    bio: "AI Researcher. Deep Learning Enthusiast. Android & Web Developer. ",
    url: "https://dsc.community.dev/pimpri-chinchwad-college-of-engineering/",
    chapterName: "Pimpri Chinchwad College Of Engineering",
    github: "https://github.com/suyashsonawane",
    linkedin: "https://www.linkedin.com/in/suyash-sonawane-44661417b/",
    twitter: "https://twitter.com/SuyashYSonawane",
    portfolio: "https://suyashsonawane.me/",
  },
  {
    longitude: 76.63243,
    latitude: 9.2023,
    batch: 2020,
    photo: ashwinraj,
    region: "Asia",
    skills: ["AI/ML", "Cloud", "IoT", "Web Dev"],
    name: "Ashwin Raj",
    bio: "Do cool things, that matter!",
    url:
      "https://dsc.community.dev/university-college-of-engineering-kariavattom/",
    chapterName: "University College of Engineering, Kariavattom",
    github: "https://github.com/ashwinraj-in",
    linkedin: "https://linkedin.com/in/rajashwin",
    twitter: "https://twitter.com/ThisIsAshwinRaj",
    portfolio: "http://ashwinraj-in.github.io/",
  },
  {
    longitude: 75.83172,
    latitude: 25.1511,
    batch: 2020,
    photo: harshKumarKhatri,
    region: "Asia",
    skills: ["Flutter", "Cloud", "Backend-Dev", "Web Dev"],
    name: "Harsh Kumar Khatri",
    bio: "Learning skills apart from knowledge.",
    url: "https://dsc.community.dev/career-point-university/",
    chapterName: "Career Point University, Kota",
    github: "https://github.com/harshkumarkhatri",
    linkedin: "https://www.linkedin.com/in/harshkumarkhatri/",
    twitter: "https://twitter.com/HarshKhatri24",
    portfolio: "http://bit.ly/iamharsh",
  },
  {
    longitude: 77.24566,
    latitude: 28.58136,
    batch: 2020,
    photo: AnmolKaur,
    region: "Asia",
    skills: ["Web Dev"],
    name: "Anmol Kaur",
    bio: "Nemophilist & Philosophile ",
    url: "https://dsc.community.dev/indraprastha-college-for-women/",
    chapterName: "Indraprastha College For Women",
    github: "https://github.com/anmolkaur18",
    linkedin: "https://in.linkedin.com/in/anmol-kaur-04ba1b190/",
    twitter: "https://twitter.com/_AnmolKaur_",
  },
  {
    longitude: 78.3236,
    latitude: 17.3457,
    batch: 2020,
    photo: venkyJayasurya,
    region: "Asia",
    skills: ["Web Dev", "UI/UX", "Cloud"],
    name: "Venkateshwara Rao Jayasurya",
    bio: "Loves to Code and Design!",
    url: "https://dsc.community.dev/vidya-jyothi-institute-of-technology/",
    chapterName: "Vidya Jyothi Institute of Technology, Hyderabad",
    github: "https://github.com/venkyjayasurya",
    linkedin: "https://www.linkedin.com/in/venky-jayasurya/",
    twitter: "https://twitter.com/venky_jayasurya/",
  },
  {
    longitude: 78.39131,
    latitude: 17.49312,
    batch: 2020,
    photo: pvsharshith,
    region: "Asia",
    skills: ["App Dev", "Web Dev"],
    name: "Harshith Pvs",
    bio: "Explorer. Techie. Open Source Enthusiast. Community Person!",
    url: "https://dsc.community.dev/jntuh-college-of-engineering-hyderabad/",
    chapterName: "JNTUH College of Engineering Hyderabad",
    github: "https://github.com/pvsharshith",
    linkedin:
      "https://www.linkedin.com/in/venkata-sai-harshith-penugonda-35aa8b160/",
    twitter: "https://twitter.com/VenkataSaiHars2",
  },
  {
    longitude: 81.85615759777016,
    latitude: 25.4324480740094,
    batch: 2020,
    photo: praddy2009,
    region: "Asia",
    skills: ["Cybersecurity", "XR", "Web Dev"],
    name: "Praddyum Verma",
    bio: "Let's talk security and Tech",
    url:
      "https://dsc.community.dev/kalinga-institute-of-industrial-technology-bhubaneswar/",
    chapterName: "Kalinga Institute of Industrial Technology",
    github: "https://github.com/praddy2009",
    linkedin: "https://linkedin.com/in/praddyum",
    twitter: "https://twitter.com/Praddyum1",
    portfolio: "https://praddy2009.github.io/portfolio/",
  },
  {
    longitude: 73.75810066610087,
    latitude: 18.645158425929512,
    batch: 2020,
    photo: akashshrivastava,
    region: "Asia",
    skills: ["Web Dev"],
    name: "Akash Shrivastava",
    bio: "Enthusiast Learner & Coder | Django Developer",
    url: "https://dsc.community.dev/dy-patil-college-of-engineering/",
    chapterName: "D.Y. Patil College of Engineering, Pune",
    github: "https://github.com/Akash1362000",
    linkedin: "https://www.linkedin.com/in/akash136/",
    twitter: "https://twitter.com/shrivastava136",
    portfolio: "https://akash1362000.github.io/",
  },
  {
    longitude: 72.8305,
    latitude: 19.0865,
    batch: 2020,
    photo: sakshigrover,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "UI/UX", "Cloud"],
    name: "Sakshi Grover",
    bio: "An artist stuck inside a coder's body!",
    url: "https://dsc.community.dev/usha-mittal-institute-of-technology/",
    chapterName: "Usha Mittal Institute of Technology",
    github: "https://github.com/sakshigrover-1998",
    linkedin: "https://linkedin.com/in/sakshi-grover-sndtwu",
    twitter: "https://twitter.com/groversakshi14",
  },
  {
		longitude: 80.886337,
		latitude: 26.846300,
		batch: 2020,
		photo: Vasundharashukla,
		region: "Asia",
		skills: ["XR", "Web Dev", "Cloud", "AI/ML"],
		name: "Vasundhara Shukla",
		bio: "Certainly the software geek who is into dancing!",
		url:"https://dsc.community.dev/the-lnm-institute-of-information-technology/",
		chapterName: "The LNM Institute of Information Technology, Jaipur",
		github: "https://github.com/Vasundharashukla",
		linkedin: "https://www.linkedin.com/in/vasundhara-shukla/",
		twitter: "https://twitter.com/VasundharaShuk9",
	},
	{
		longitude: 72.837761,
		latitude: 19.224100,
		batch: 2020,
		photo: palak,
		region: "Asia",
		skills: ["App Dev", "Web Dev", "Cloud", "AI/ML"],
		name: "Palak Mantry",
		bio: "Morgan Stanley Intern'21 | Interested in Problem Solving and Full Stack Development",
		url: "https://dsc.community.dev/veermata-jijabai-technological-institute/",
		chapterName: "Veermata Jijabai Technological Institute",
		github: "https://github.com/pal-16",
		linkedin: "https://linkedin.com/in/palak-mantry",
		twitter: "https://twitter.com/MantryPalak",
	},
	{
    longitude: 77.620540,
    latitude: 13.079790,
    batch: 2020,
    photo: akshita2k,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "AI/ML", "Cloud"],
    name: "Akshita Sharma",
    bio: "I enjoy learning and exploring new vistas of Technology while also sharing the knowledge among my peers!",
    url: "https://dsc.community.dev/dayananda-sagar-academy-of-technology-and-management/",
    chapterName: "Dayananda Sagar Academy of Technology and Management",
    github: "https://github.com/akshita2k",
    linkedin: "https://linkedin.com/in/akshita-sharma-15a703111",
    instagram: "https://instagram.com/akshi_4446",
    portfolio: "https://akshita2k.github.io"
  },
  {
		longitude: 91.666740,
		latitude: 26.154620,
		batch: 2020,
		photo: subratkishoredutta,
		region: "Asia",
		skills: ["AI/ML"],
		name: "Subrat Kishore Dutta",
		bio: "AI research enthusiast",
		url:
			"https://dsc.community.dev/assam-engineering-college-jalukbari/",
		chapterName: "Assam Engineering College",
		github: "https://github.com/subratkishoredutta",
		linkedin: "https://linkedin.com/in/subrat-kishore-dutta-70a9a316b",
	},
{
    longitude: 83.2184815,
    latitude: 17.6868159,
    batch: 2020,
    photo: ikoala21,
    region: "Asia",
    skills: ["AI/ML", "Web Dev"],
    name: "Manasa Kalaga",
    bio: "I mount my soul at /dev/null",
    url: "https://dsc.community.dev/gvp-college-of-engineering/",
    chapterName: "GVP College of Engineering",
    github: "https://github.com/ikoala21",
    linkedin: "https://www.linkedin.com/in/manasa-kalaga/",
    twitter: "https://twitter.com/ikoala21",
},
	{
        "latitude": 28.666450,
        "longitude": 77.231390,
        "batch": 2020,
        "photo": sangeetajha,
        "region": "Asia",
        "skills": ["Web Dev", "UI/UX", "Cloud"],
        "name": "Sangeeta Jha",
        "bio": "Always open for opportunities and love exploring new technologies",
        "url": "https://dsc.community.dev/indira-gandhi-delhi-technical-university-for-women/",
        "chapterName": "Indira Gandhi Delhi Technical University for Women",
        "github": "https://github.com/nehasangeetajha",
        "linkedin": "https://www.linkedin.com/in/sangeeta-jha-765232142/",
        "twitter": "https://twitter.com/nehasangeetajha",
        "portfolio": "http://sangeeta-jha.web.app/"
},
	{
        "latitude": 35.811914,
        "longitude": 10.638553,
        "batch": 2020,
        "photo": taharh,
        "region": "North Africa",
        "skills": ["AI/ML","App Dev", "Cloud"],
        "name": "Taha Rehah",
        "bio": "Explorer,Open Source Enthusiast, Community Person, Tensorflow Developer!",
        "url": "https://dsc.community.dev/higher-institute-of-applied-science-and-technology/",
        "chapterName": "Higher Institute of Applied Science and Technology of Sousse",
        "github": "https://github.com/taharh",
        "linkedin": "https://linkedin.com/in/taha-rehah",
        "twitter": "https://twitter.com/TahaRehah"
  },
	{
        "latitude": 12.873014,
        "longitude": 80.221892,
        "batch": 2020,
        "photo": AkashM,
        "region": "Asia",
        "skills": ["Web Dev", "UI/UX", "Cybersecurity"],
        "name": "Akash M",
        "bio": "Yet another developer",
        "url": "https://dsc.community.dev/sathyabama-institute-of-science-technology/",
        "chapterName": "Sathyabama Institute of Science and Technology",
        "github": "https://github.com/AkashM398",
        "linkedin": "https://www.linkedin.com/in/akashm398",
        "twitter": "https://twitter.com/akashm398",
        "portfolio": "https://akashbuild.tech/"
  }
];

export default data;
