//import pictures
import abhinavsri360 from "../../photos/abhinavsri360.jpg";
import AravindVNair99 from "../../photos/AravindVNair99.jpg";
import srilaasya from "../../photos/srilaasya.jpg";
import Aswin from "../../photos/Aswin.jpg";
import helios027 from "../../photos/helios027.jpg";
import shawavisek35 from "../../photos/shawavisek35.png";
import karthik from "../../photos/karthik.jpg";
import MuhammadHassanRazaa from "../../photos/MuhammadHassanRazaa.jpg";
import advaithunnikrishnan from "../../photos/advaithunnikrishnan.jpg";
import AsishRaju from "../../photos/AsishRaju.jpg";
import Aineshphanithi from "../../photos/Aineshphanithi.jpg";
import chrisft25 from "../../photos/chrisft25.jpg";
import subratkishoredutta from "../../photos/subratkishoredutta.jpg";
const data = [
	{
		longitude: 77.3653,
		latitude: 28.5192,
		batch: 2020,
		photo: abhinavsri360,
		region: "Asia",
		skills: ["App Dev", "Web Dev", "UI/UX", "Cloud"],
		name: "Abhinav Srivastava",
		bio: "I write something colorful on something very dark.",
		url:
			"https://dsc.community.dev/jaypee-institute-of-information-technology-sec-128",
		chapterName: "Jaypee Institute of Information Technology, Sec - 128",
		github: "https://github.com/abhinavsri360",
		linkedin: "https://linkedin.com/in/abhinavsri360",
		twitter: "https://twitter.com/abhinavsri360",
		portfolio: "https://abhinavsri360.netlify.app",
	},
	{
		longitude: 91.666740,
		latitude: 26.154620,
		batch: 2020,
		photo: subratkishoredutta,
		region: "Asia",
		skills: ["AI/ML"],
		name: "Subrat Kishore Dutta",
		bio: "AI research enthusiast",
		url:
			"https://dsc.community.dev/assam-engineering-college-jalukbari/",
		chapterName: "Jaypee Institute of Information Technology, Sec - 128",
		github: "https://github.com/subratkishoredutta",
		linkedin: "https://www.linkedin.com/in/subrat-kishore-dutta-70a9a316b/",
	},
	{
		longitude: 83.2184815,
		latitude: 17.6868159,
		batch: 2020,
		photo: srilaasya,
		region: "Asia",
		skills: ["AI/ML", "Web Dev", "UI/UX"],
		name: "Sri Laasya Nutheti",
		bio: "Respect Existance or Expect Resistance",
		url:
			"https://dsc.community.dev/andhra-university-college-of-engineering",
		chapterName: "Andhra University College of Engineering",
		github: "https://github.com/srilaasya",
		linkedin: "https://linkedin.com/in/sri-laasya",
		twitter: "https://twitter.com/n_sri_laasya",
	},
	{
		longitude: 77.6746238,
		latitude: 12.8950888,
		batch: 2020,
		photo: AravindVNair99,
		region: "Asia",
		skills: ["Web Dev", "Cloud"],
		name: "Aravind V. Nair",
		bio:
			"Full-stack Web Developer, Cloud Computing and Cybersecurity Enthusiast",
		url: "https://dsc.community.dev/amrita-school-of-engineering-bengaluru",
		chapterName: "Amrita School of Engineering, Bengaluru",
		github: "https://github.com/AravindVNair99",
		linkedin: "https://linkedin.com/in/AravindVNair99",
		twitter: "https://twitter.com/AravindVNair99",
	},
	{
		"longitude": 77.035270,
		"latitude": 28.609570,
		"batch": 2020,
		"photo": Aswin,
		"region": "Asia",
		"skills": ["Cloud"],
		"name": "Aswin Kumar M",
		"bio": "Never fear the Air.",
		"url": "https://dsc.community.dev/bannari-amman-institute-of-technology/",
		"chapterName": "Bannari Amman Institute of Technology, Sathyamangalam",
		"github": "https://github.com/todcru",
		"linkedin": "https://www.linkedin.com/in/aswin-kumar-m-83081b171/",
		"twitter": "https://twitter.com/thisaswin"
	},
	{
		longitude: 86.9842256,
		latitude: 25.242453,
		batch: 2020,
		photo: helios027,
		region: "Asia",
		skills: ["Web Dev"],
		name: "Harsh Jain",
		bio: "Progate Community Intern",
		url: "https://dsc.community.dev/bhagalpur-college-of-engineering",
		chapterName: "Indian Institute of Information Technology, Bhagalpur",
		github: "https://github.com/helios027",
		linkedin: "https://linkedin.com/in/harshjain2710",
		twitter: "https://twitter.com/HarshJain027",
	},
	{
		longitude: 88.35736,
		latitude: 22.58969,
		batch: 2020,
		photo: shawavisek35,
		region: "Asia",
		skills: ["App Dev", "Web Dev", "UI/UX", "Cloud", "Machine Learning"],
		name: "Avisek Shaw",
		bio: "Commit the changes in your life otherwise you will loose them.",
		url:
			"https://dsc.community.dev/calcutta-institute-of-engineering-and-management",
		chapterName: "Calcutta Institute of Engineering and Management",
		github: "https://github.com/shawavisek35",
		linkedin: "https://linkedin.com/in/avisek-shaw-78136b196",
		twitter: "https://twitter.com/AvisekShaw6",
		portfolio: "https://avisekcode.netlify.app",
	},
	{
		longitude: 77.5945627,
		latitude: 12.9715987,
		batch: 2020,
		photo: karthik,
		region: "Asia",
		skills: ["Bleh"],
		name: "B K Karthik",
		bio: "ಠ益ಠ.",
		url: "https://dsc.community.dev/pes-university-ec-campus",
		chapterName: "PES University Electronic City Campus",
		github: "https://github.com/call-me-bk",
		linkedin: "https://linkedin.com/in/iamKarthikBK",
		twitter: "https://twitter.com/iamKarthikBK",
		portfolio: "https://www.nohello.com",
	},
	{
		longitude: 21.640339625980996,
		latitude: 47.54352832810872,
		batch: 2020,
		photo: MuhammadHassanRazaa,
		region: "Europe",
		skills: ["App Dev","AI/ML"],
		name: "Muhammad Hassan Raza",
		bio: "A hardworking and resourceful individual seeking to work as a computer scientist with the ability to persuade and convince people about computer-related works.",
		url: "dsc.community.dev/university-of-debrecen-debreceni-egyetem-de/",
		chapterName: "University of Debrecen / Debreceni Egyetem DE",
		github: "https://github.com/MuhammadHassanRazaa",
		linkedin: "https://linkedin.com/in/sshthassanraza",
		twitter: "https://twitter.com/sshthassanraza"
  },
  {
		"longitude": 76.990746,
		"latitude": 8.549941,
		"batch": 2020,
		"photo": advaithunnikrishnan,
		"region": "Asia",
		"skills": ["Web Dev"],
		"name": "Advaith U",
		"bio": "Web Developer",
		"url": "https://dsc.community.dev/mar-baselios-college-of-engineering-technology/",
		"chapterName": "Mar Baselios College of Engineering and Technology",
		"github": "https://github.com/advaith-unnikrishnan",
		"linkedin": "https://linkedin.com/in/advaithu",
		"twitter": "https://twitter.com/advaith_unni",
		"portfolio": "https://advaithunnikrishnan.me"
	},
	{
		longitude: 83.376702,
		latitude: 17.781218,
		batch: 2020,
		photo: AsishRaju,
		region: "Asia",
		skills: ["Web Dev", "UI/UX",],
		name: "V Asish Raju",
		bio: "I would love to change the world, but they won’t give me the source code",
		url: "https://dsc.community.dev/gandhi-institute-of-technology-and-management-visakhapatnam-campus/",
		chapterName: "GITAM University, Vizag Campus",
		github: "https://github.com/AsishRaju",
		linkedin: "https://linkedin.com/in/asishraju",
		twitter: "https://twitter.com/asish_io"
	},
	{
		longitude: 78.337764,
		latitude: 17.465592,
		batch: 2020,
		photo: Aineshphanithi,
		region: "Asia",
		skills: ["Cloud", "UI/UX"],
		name: "Ainesh Phanithi",
		bio:
			"Engineering student and working towards software development. Can effortlessly articulate ideas, offer practical solutions and has a great sense of humour.",
		url: "https://dsc.community.dev/cvr-college-of-engineering",
		chapterName: "CVR College of Engineering",
		github: "https://github.com/Aineshphanithi",
		linkedin: "https://www.linkedin.com/in/ainesh-phanithi/",
		twitter: "https://twitter.com/"
  },
  {
        "longitude": -88.177773,
        "latitude": 13.481270,
        "batch": 2020,
        "photo": chrisft25,
        "region": "South America",
        "skills": ["Web Dev", "UI/UX"],
        "name": "Christopher Fuentes",
        "bio": "Backend Developer. Geek. Marketing enthusiast. Passionate about learning new stuff. ",
        "url": "https://dsc.community.dev/universidad-gerardo-barrios",
        "chapterName": "Universidad Gerardo Barrios",
        "github": "https://github.com/chrisft25",
        "linkedin": "https://linkedin.com/in/chrisft25",
        "twitter": "https://twitter.com/chrisft25",
        "portfolio": "https://chrisfuentes.me"
	}
];
export default data;
