//import pictures
import abhinavsri360 from "../../photos/abhinavsri360.jpg";
import AravindVNair99 from "../../photos/AravindVNair99.jpg";
import srilaasya from "../../photos/srilaasya.jpg";
import Aswin from "../../photos/Aswin.jpg";
import helios027 from "../../photos/helios027.jpg";
import shawavisek35 from "../../photos/shawavisek35.png";
import karthik from "../../photos/karthik.jpg";
import felirox from "../../photos/niran.jpeg";

const data = [
	{
		longitude: 77.3653,
		latitude: 28.5192,
		batch: 2020,
		photo: abhinavsri360,
		region: "Asia",
		skills: ["App Dev", "Web Dev", "UI/UX", "Cloud"],
		name: "Abhinav Srivastava",
		bio: "I write something colorful on something very dark.",
		url:
			"https://dsc.community.dev/jaypee-institute-of-information-technology-sec-128",
		chapterName: "Jaypee Institute of Information Technology, Sec - 128",
		github: "https://github.com/abhinavsri360",
		linkedin: "https://linkedin.com/in/abhinavsri360",
		twitter: "https://twitter.com/abhinavsri360",
		portfolio: "https://abhinavsri360.netlify.app",
	},
	{
		longitude: 83.2184815,
		latitude: 17.6868159,
		batch: 2020,
		photo: srilaasya,
		region: "Asia",
		skills: ["AI/ML", "Web Dev", "UI/UX"],
		name: "Sri Laasya Nutheti",
		bio: "Respect Existance or Expect Resistance",
		url:
			"https://dsc.community.dev/andhra-university-college-of-engineering",
		chapterName: "Andhra University College of Engineering",
		github: "https://github.com/srilaasya",
		linkedin: "https://linkedin.com/in/sri-laasya",
		twitter: "https://twitter.com/n_sri_laasya",
	},
	{
		longitude: 77.6746238,
		latitude: 12.8950888,
		batch: 2020,
		photo: AravindVNair99,
		region: "Asia",
		skills: ["Web Dev", "Cloud"],
		name: "Aravind V. Nair",
		bio:
			"Full-stack Web Developer, Cloud Computing and Cybersecurity Enthusiast",
		url: "https://dsc.community.dev/amrita-school-of-engineering-bengaluru",
		chapterName: "Amrita School of Engineering, Bengaluru",
		github: "https://github.com/AravindVNair99",
		linkedin: "https://linkedin.com/in/AravindVNair99",
		twitter: "https://twitter.com/AravindVNair99",
	},
	{
		"longitude":11.5034,
		"latitude": 77.2444,
		"batch": 2020,
		"photo": Aswin,
		"region": "Asia",
		"skills": [ "Cloud"],
		"name": "Aswin Kumar M",
		"bio": "Never fear the Air.",
		"url": "https://dsc.community.dev/bannari-amman-institute-of-technology/",
		"chapterName": "Bannari Amman Institute of Technology, Sathyamangalam",
		"github": "https://github.com/todcru",
		"linkedin": "https://www.linkedin.com/in/aswin-kumar-m-83081b171/",
		"twitter": "https://twitter.com/thisaswin"
	},
	{
		longitude: 86.9842256,
		latitude: 25.242453,
		batch: 2020,
		photo: helios027,
		region: "Asia",
		skills: ["Web Dev"],
		name: "Harsh Jain",
		bio: "Progate Community Intern",
		url: "https://dsc.community.dev/bhagalpur-college-of-engineering",
		chapterName: "Indian Institute of Information Technology, Bhagalpur",
		github: "https://github.com/helios027",
		linkedin: "https://linkedin.com/in/harshjain2710",
		twitter: "https://twitter.com/HarshJain027",
	},
  {
		longitude: 77.63461076853751,
		latitude: 13.117017226569963,
		batch: 2020,
		photo: felirox,
		region: "Asia",
		skills: ["IoT","Deep Learning","Cybersecurity"],
		name: "Niran N",
		bio: "Cybersecurity Teaching Assistant at RACE | IEEE SB Vice Chair | Core - Coders & Hackathon Club",
		url: "https://dsc.community.dev/reva-university/",
		chapterName: "REVA University",
		github: "https://github.com/felirox",
		linkedin: "https://www.linkedin.com/in/felirox/",
		twitter: "https://twitter.com/feliroxx",
	},
	{
		longitude: 88.35736,
		latitude: 22.58969,
		batch: 2020,
		photo: shawavisek35,
		region: "Asia",
		skills: ["App Dev", "Web Dev", "UI/UX", "Cloud", "Machine Learning"],
		name: "Avisek Shaw",
		bio: "Commit the changes in your life otherwise you will loose them.",
		url:
			"https://dsc.community.dev/calcutta-institute-of-engineering-and-management",
		chapterName: "Calcutta Institute of Engineering and Management",
		github: "https://github.com/shawavisek35",
		linkedin: "https://linkedin.com/in/avisek-shaw-78136b196",
		twitter: "https://twitter.com/AvisekShaw6",
		portfolio: "https://avisekcode.netlify.app",
	},
	{
		longitude: 12.8625611,
		latitude: 77.6656671,
		batch: 2020,
		photo: karthik,
		region: "Asia",
		skills: ["Bleh"],
		name: "B K Karthik",
		bio: "ಠ益ಠ.",
		url: "https://dsc.community.dev/pes-university-ec-campus",
		chapterName: "PES University Electronic City Campus",
		github: "https://github.com/call-me-bk",
		linkedin: "https://linkedin.com/in/iamKarthikBK",
		twitter: "https://twitter.com/iamKarthikBK",
		portfolio: "https://www.nohello.com",
	}
];
export default data;
